# Generated by Django 3.0.6 on 2020-05-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('FULL_DAY', 'FULL_DAY'), ('HALF_DAY', 'HALF_DAY')], max_length=255, null=True),
        ),
    ]
