# Generated by Django 3.0.5 on 2020-05-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200508_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='names',
        ),
    ]
