# Generated by Django 3.0.5 on 2020-06-10 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200518_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 10, 11, 34, 33, 789776, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
