# Generated by Django 3.0.5 on 2020-06-10 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200610_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 10, 11, 41, 46, 300296, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
