# Generated by Django 3.0.5 on 2020-06-11 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20200610_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 11, 12, 6, 23, 609996, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
