# Generated by Django 3.0.5 on 2020-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20200611_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateField(auto_now_add=True),
        ),
    ]
