# Generated by Django 3.0.5 on 2020-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20200612_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='current_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='name'),
        ),
    ]
