# Generated by Django 3.0.5 on 2020-06-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20200612_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profile'),
        ),
    ]
