# Generated by Django 3.0.5 on 2020-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20200612_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='city',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
        migrations.AddField(
            model_name='state',
            name='names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
