# Generated by Django 3.0.5 on 2020-06-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20200612_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='names',
            new_name='name',
        ),
    ]
